import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@immu/components/index";
import { Murecho } from "next/font/google";

// Configurar a fonte Murecho
const murecho = Murecho({
  subsets: ["latin"],
  weight: ["300", "400", "700"], // Adicione os pesos desejados
  variable: "--font-murecho",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={murecho.variable}>
      <body className="antialiased font-murecho">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

